shortName: agof
fullName: AnsibleGitopsFramework
repo: https://github.com/validatedpatterns/agof
webHookName: ''
owners:
  - U02A161R524 # martjack
triggers:
  branches:
  - name: v1
    versions:
    - 'none'

  openshift:
  - version: 'none'
    branch: v1
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
