shortName: aegitops
fullName: AnsibleEdgeGitops
repo: https://github.com/validatedpatterns/ansible-edge-gitops
webHookName: ''
owners:
  - martjack
triggers:
  branches:
  - name: 'v1.4'
    versions:
    - '4.18'
  - name: 'v2.0'
    versions:
    - '4.21'
    - '4.20'

  openshift:
  - version: '4.21'
    branch: 'v2.0'
    platforms:
      - aws
    buildType: stable
  - version: '4.20'
    branch: 'v2.0'
    platforms:
      - aws
    buildType: stable
  - version: '4.18'
    branch: 'v1.4'
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: gitops
    branch: main
  - name: ansible_platform
    branch: main
  - name: odf
    branch: main
  - name: cnv
    branch: main
