shortName: aegitops
fullName: AnsibleEdgeGitops
webHookName: ''
owners:
  - Martin Jackson
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
  - name: 'v1.2'
    versions:
    - '4.12'
    - '4.11'
    - '4.10'

  openshift:
  - version: '4.12'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.11'
    branch: 'v1.2'
    platforms:
      - aws
    buildType: stable
  - version: '4.10'
    branch: 'v1.2'
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: openshift-gitops
    branch: main
