shortName: dummytest
fullName: DummyTest
repo: https://github.com/validatedpatterns/dummytest
webHookName: ''
owners:
  - UV196F5U3 # mlabonte
triggers:
  branches:
  - name: main
    versions:
    - 'none'

  openshift:
  - version: 'none'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
