shortName: manuela
fullName: Manuela
webHookName: ''
owners:
  - claudiol
triggers:
  branches:
  - name: main
    versions:
    - '4.13'
  - name: 'v2.3'
    versions:
    - '4.12'
    - '4.11'
    - '4.10'

  openshift:
  - version: '4.13'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.12'
    branch: 'v2.3'
    platforms:
      - aws
    buildType: stable
  - version: '4.11'
    branch: 'v2.3'
    platforms:
      - gcp
    buildType: stable
  - version: '4.10'
    branch: 'v2.3'
    platforms:
      - azure
    buildType: stable

  subscriptions:
  - name: gitops
    branch: main
  - name: rhacm
    branch: main
