shortName: industrialedge
fullName: IndustrialEdge
repo: https://github.com/validatedpatterns/industrial-edge
webHookName: ''
owners:
  - U02A161R524 # martjack
triggers:
  branches:
  - name: main
    versions:
    - '4.18'
    - '4.17'
    - '4.16'

  openshift:
  - version: '4.18'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.17'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.16'
    branch: main
    platforms:
      - azure
    buildType: stable

  subscriptions:
  - name: none
    branch: none
