shortName: medicaldiag
fullName: MedicalDiagnosis
repo: https://github.com/validatedpatterns/medical-diagnosis
webHookName: 'medical-diagnosis'
owners:
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.13'
  - name: 'v2.5'
    versions:
    - '4.12'
    - '4.11'

  openshift:
  - version: '4.13'
    branch: main
    platforms:
      - gcp
    buildType: stable
  - version: '4.12'
    branch: 'v2.5'
    platforms:
      - azure
    buildType: stable
  - version: '4.11'
    buildType: stable
    branch: 'v2.5'
    platforms:
      - aws

  github:
    - version: '4.11'
      platforms:
        - azure

  subscriptions:
  - name: gitops
    branch: main
  - name: amq_streams
    branch: main
  - name: serverless
    branch: main
  - name: odf
    branch: main
