shortName: devsecops
fullName: MulticlusterDevSecOps
webHookName: ''
owners:
  - whenry
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.13'
    - '4.12'
    - '4.11'

  openshift:
  - version: '4.13'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.12'
    branch: main
    platforms:
      - gcp
    buildType: stable
  - version: '4.11'
    branch: main
    platforms:
      - azure
    buildType: stable

  subscriptions:
  - name: gitops
    branch: main
  - name: rhacm
    branch: main
  - name: odf
    branch: main
  - name: rhacs
    branch: main
  - name: quay
    branch: main
  - name: quay-bridge
    branch: main
  - name: pipelines
    branch: main
