shortName: devsecops
fullName: MulticlusterDevSecOps
webHookName: ''
owners:
  - whenry
  - jrickard
triggers:
  branches:
  - name: main
    versions:
    - '4.12'
    - '4.11'
    - '4.10'

  openshift:
  - version: '4.12'
    branch: main
    platforms:
      - gcp
  - version: '4.11'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.10'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - openshift-gitops: main

