shortName: mcgitops
fullName: MultiCloudGitops
repo: https://github.com/validatedpatterns/multicloud-gitops
webHookName: ''
owners:
  - mbaldess
triggers:
  branches:
  - name: main
    versions:
    - '4.18'
    - '4.17'
    - '4.16'

  openshift:
  - version: '4.18'
    branch: main
    platforms:
      - azure
    buildType: stable
  - version: '4.17'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.16'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: gitops
    branch: main
  - name: rhacm
    branch: main
