shortName: mcgitopsstandalone
fullName: MultiCloudGitopsStandalone
repo: https://github.com/validatedpatterns/multicloud-gitops
webHookName: ''
owners:
  - mbaldess
triggers:
  branches:
  - name: main
    versions:
    - '4.21'
    - '4.20'
    - '4.18'

  openshift:
  - version: '4.21'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.20'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.18'
    branch: main
    platforms:
      - gcp
    buildType: stable

  subscriptions:
  - name: none
    branch: none
