shortName: mcgitopsstandalone
fullName: MultiCloudGitopsStandalone
repo: https://github.com/validatedpatterns/multicloud-gitops
webHookName: ''
owners:
  - mbaldess
triggers:
  branches:
  - name: main
    versions:
    - '4.17'
    - '4.16'

  openshift:
  - version: '4.17'
    branch: main
    platforms:
      - gcp
    buildType: stable
  - version: '4.16'
    branch: main
    platforms:
      - azure
    buildType: stable

  subscriptions:
  - name: none
    branch: none
