shortName: openshiftai
fullName: OpenShiftAI
repo: https://github.com/validatedpatterns-sandbox/openshift-ai
webHookName: ''
owners:
  - jrickard
triggers:
  branches:
  - name: rhoai
    versions:
    - '4.19'
    - '4.18'

  openshift:
  - version: '4.19'
    branch: rhoai
    platforms:
      - aws
      - baremetal
    buildType: stable
  - version: '4.18'
    branch: rhoai
    platforms:
      - aws
      - baremetal
    buildType: stable
