shortName: openshiftai
fullName: OpenShiftAI
repo: https://github.com/validatedpatterns-sandbox/openshift-ai
webHookName: ''
owners:
  - jrickard
triggers:
  branches:
  - name: rhoai
    versions:
    - '4.22'
    - '4.21'
    - '4.20'

  openshift:
  - version: '4.22'
    branch: rhoai
    platforms:
      - aws
      - baremetal
    buildType: stable
    ocpTrigger: false
  - version: '4.21'
    branch: rhoai
    platforms:
      - aws
      - baremetal
    buildType: stable
    ocpTrigger: false
  - version: '4.20'
    branch: rhoai
    platforms:
      - aws
      - baremetal
    buildType: stable
    ocpTrigger: false
