shortName: patternsoperator
fullName: PatternsOperator
repo: https://github.com/validatedpatterns/patterns-operator
webHookName: ''
owners:
  - mbaldess
triggers:
  branches:
  - name: main
    versions:
    - '4.20'
    - '4.19'
    - '4.18'

  openshift:
  - version: '4.20'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.19'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.18'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
