shortName: ragllm
fullName: RAG-LLM
repo: https://github.com/validatedpatterns/rag-llm-gitops
webHookName: ''
owners:
  - dminnear
triggers:
  branches:
  - name: main
    versions:
    - '4.20'
    - '4.19'
    - '4.18'

  openshift:
  - version: '4.20'
    branch: main
    platforms:
      - aws
      - azure
  - version: '4.19'
    branch: main
    platforms:
      - aws
  - version: '4.18'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: nfd
    branch: main
