shortName: retail
fullName: Retail
repo: https://github.com/validatedpatterns/retail
webHookName: ''
owners:
  - martjack
triggers:
  branches:
  - name: main
    versions:
    - '4.18'
    - '4.17'
    - '4.16'

  openshift:
  - version: '4.18'
    branch: main
    platforms:
      - aws
  - version: '4.17'
    branch: main
    platforms:
      - aws
    buildType: stable
  - version: '4.16'
    branch: main
    platforms:
      - aws
    buildType: stable

  subscriptions:
  - name: none
    branch: none
