FROM fedora:latest

RUN  dnf install --no-docs -y \
    golang \
    git \
    make && \
    dnf clean all

WORKDIR /root

RUN git clone https://github.com/openshift/hive && \
cd hive && \
make build-hiveutil && \
install -m 0755 bin/hiveutil /usr/local/bin && \
rm -rf /root/hive && \
rm -rf /root/.cache

WORKDIR /root

CMD /usr/local/bin/hiveutil
