FROM quay.io/centos/centos:stream9 AS builder

# Default is set in Makefile
ARG HUGO_VERSION

# Temporary hack because extras-common repo seems to be busted
RUN dnf --disablerepo=extras-common install -y 'dnf-command(config-manager)' && dnf config-manager --set-disabled extras-common && dnf clean all

RUN dnf install -y --allowerasing git-core golang ruby curl cmake gcc && dnf clean all
RUN mkdir -p /tmp/hugodl && cd /tmp/hugodl && \
  curl -L -O "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_${HUGO_VERSION}_linux-amd64.tar.gz" && \
  tar xf "hugo_${HUGO_VERSION}_linux-amd64.tar.gz" && \
  mv hugo /usr/local/bin/hugo && \
  chmod 0755 /usr/local/bin/hugo && \
  rm -rf /tmp/hugodl

RUN curl https://htmltest.wjdp.uk | bash -s -- -b /usr/local/bin
RUN mkdir -p /tmp/rubybuild && cd /tmp/rubybuild && \
  gem install bundler && echo -e 'source "https://rubygems.org"\ngem "asciidoctor"\ngem "rouge"\n' > Gemfile && \
  bundle install
EXPOSE 4000

WORKDIR /site

ENTRYPOINT [ "/bin/bash" ]
