FROM registry.access.redhat.com/ubi10/ubi-minimal

# Default is set in Makefile
ARG HUGO_VERSION="0.133.1"
ARG TARGETARCH
ARG ALTTARGETARCH

# Temporary hack because extras-common repo seems to be busted
RUN microdnf install -y --nodocs --setopt=install_weak_deps=0 \
    curl tar gzip zip git ruby ruby-devel gcc gcc-c++ make \
 && curl -fsSL "https://github.com/gohugoio/hugo/releases/download/v${HUGO_VERSION}/hugo_extended_${HUGO_VERSION}_linux-${TARGETARCH}.tar.gz" \
    | tar -xzC /usr/local/bin hugo \
 && chmod +x /usr/local/bin/hugo \
 && curl -fsSL https://htmltest.wjdp.uk | bash -s -- -b /usr/local/bin \
 && gem install --no-document asciidoctor rouge \
 && microdnf remove -y ruby-devel gcc gcc-c++ make \
 && microdnf clean all \
 && rm -rf /var/cache/yum

RUN git config --system --add safe.directory '*'

EXPOSE 4000

WORKDIR /site

ENTRYPOINT [ "/bin/bash" ]
