FROM ruby:2-alpine as jekyll

RUN apk add --no-cache build-base gcc bash cmake git gcompat curl
RUN curl -L -o /usr/local/bin/proof-html.rb https://raw.githubusercontent.com/anishathalye/proof-html/master/proof-html.rb && chmod +x /usr/local/bin/proof-html.rb
# install both bundler 1.x and 2.x incase you're running
# old gem files
# https://bundler.io/guides/bundler_2_upgrade.html#faq
RUN gem install bundler -v "~>1.0" && gem install bundler jekyll jekyll-paginate just-the-docs html-proofer

EXPOSE 4000

WORKDIR /site

ENTRYPOINT [ "/bin/bash" ]
