FROM fedora:latest

RUN  dnf install --no-docs -y \
    golang \
    git \
    make && \
    dnf clean all

WORKDIR /root

RUN git clone https://github.com/openshift/hypershift && \
cd hypershift && \
make build && \
install -m 0755 bin/hypershift /usr/local/bin && \
rm -rf /root/hypershift && \
rm -rf /root/.cache

WORKDIR /root

CMD /usr/local/bin/hypershift
